# Generated by Django 5.1.3 on 2024-12-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoloatendimento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
